### ISSUE TITLE
Error with input file when using lammps_logplotter in command line interface for plotting

### ISSUE THREAD

**Issue by qqlovekerry** [henriasv/lammps-logfile#15]
Hello,

I think I followed the manual and used the command `lammps_logplotter -x Step -y Temp streitz/log.lammps`  to plot the log file.

However, I always encounter the following error:

```
usage: lammps_logplotter [-h] [-x X] [-y Y [Y ...]] [-a RUNNING_AVERAGE]
                         input_file
lammps_logplotter: error: the following arguments are required: input_file
```

Could you kindly guide me on how to resolve this issue? Any assistance would be greatly appreciated!

**Comment by henriasv** [comment]
Hi, this seems to be due to how argparse sorts positional arguments and keyword arguments. It seems that there is a discrepancy between this sorting and the usage string that is created.

**Comment by qqlovekerry** [comment]
Hello,

Thank you very much for your reply!

With the help of your previous answer to my email, I changed the usage to `lammps_logplotter log.lammps -x Step -y Temp`, and it works perfectly now.

Maybe only the description for the usage needs to be modified.

I appreciate your guidance very much on this!
